name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        go: ["1.15", "1.16", "1.17"]
    steps:
      - uses: actions/checkout@v2

      # Install Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      # Run tests
      - name: Test
        run: go test ./... -v

      # Run gosec
      - name: Install gosec
        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
        if: runner.os == 'Linux'
      - name: Run gosec
        run: gosec ./...
        if: runner.os == 'Linux'
